### PR TITLE
initial commit of lidarr-smloadr2

### PR DESCRIPTION
**Pull request by permutationalparody**
updated readme
added .gitignore
added sample config file

### CODE REVIEW

**Comment by theg00s3** [comment]
This looks good! The inability of the script to only select the albums that lidarr returns is why I had to nerf my personal copy of the script.

**Comment by permutationalparody** [comment]
Hi, i hope you find it useful. The fact that the old script tried to download every album by every artist contained in lidarr was the reason i wrote it.

**Comment by Migz93** [comment]
Hello permutationalparody,

Sorry for the late reply on this, i never seem to get notifications from git.
I've had a quick look, this looks awesome and 10000x better/cleaner then what i'd cobbled together!
I did try to pick this script back up to implement only grabbing wanted albums but never had enough time so very thankful for your work on this and the perk of having lidarr import things is even better.

Will try get some time over the weekend to run through the script and will then merge the PR. :).

**Comment by Migz93** [comment]
Ran through this, your modified version works so much better, the code is much cleaner & the process it goes through now is great
I think i'm going to have to remove all the music i'd downloaded previously and download it again using your version of the script.
Thanks so much for your work on this, happy to see people taking my initial idea and improving it beyond what i was capable of.

**Comment by permutationalparody** [comment]
Sorry for the late reply, I have been a bit busy with RL stuff. 
Im glad my contribution was received so warmly. Time permitting if there are any further improvements i can make, i would be happy to try.

**Pull request merged**
